const CourseActionTypes = {
  UPDATE_COURSES: "UPDATE_COURSES",
  ENROLL_COURSE: "ENROLL_COURSE",
  FETCH_COURSES_START: 'FETCH_COURSES_START',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAILURE: 'FETCH_COURSES_FAILURE'
};

export default CourseActionTypes;
